version: '2'

networks:
  monitoring:
  vps:
    external: true

services:

  influxdb:
    image: influxdb:1.4
    networks:
      - monitoring
      - vps
    environment:
      - INFLUXDB_DB="telegraf"
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=${TELEGRAF_PASSWORD}
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    labels:
      - "traefik.enable=true"
      - "traefik.backend=influxdb"
      - "traefik.docker.network=vps"
      - "traefik.port=8086"
      - "traefik.frontend.rule=Host:influxdb.mgen-extension.fr"

  telegraf:
    image: telegraf:1.5
    networks:
      - monitoring
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock

  grafana:
    image: grafana/grafana:4.6.3
    networks:
      - monitoring
      - vps
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${GRAFANA_SMTP_HOST}
      - GF_SMTP_USER=${GRAFANA_SMTP_USER}
      - GF_SMTP_PASSWORD=${GRAFANA_SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${GRAFANA_SMTP_FROM_ADDRESS}
      - GF_SMTP_FROM_NAME=${GRAFANA_SMTP_FROM_NAME}
    volumes:
      - ./data/grafana:/var/lib/grafana
    links:
      - influxdb
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.docker.network=vps"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:grafana.mgen-extension.fr"
